/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 cdmusic.gltf --transform
Author: mfb64 (https://sketchfab.com/mfb64)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cd-music-02-a6d227d2b83a4fb2b3d5099e46ed6838
Title: CD Music 02
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cdmusic-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_5_1.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_6_1.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['cover_cd.001']} position={[-0.235, 0.002, 0.199]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial001} position={[-0.235, 0.002, 0.199]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['cover_back.001']} position={[-0.24, -0.02, 0.147]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['cover_front.001']} position={[-0.246, 0.042, 0.199]} rotation={[0, 0, -Math.PI / 3]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials['cover_back.002']} position={[0.06, 0.115, 0.03]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials['cover_front.002']} position={[0.064, 0.063, 0.057]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['cover_back.003']} position={[0.14, 0.115, 0.04]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['cover_front.003']} position={[0.144, 0.063, 0.067]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials['cover_back.004']} position={[0.22, 0.115, 0.05]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_43.geometry} material={materials['cover_front.004']} position={[0.224, 0.063, 0.077]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials['cover_back.005']} position={[0.3, 0.115, 0.06]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials['cover_front.005']} position={[0.304, 0.063, 0.087]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_63.geometry} material={materials['cover_back.006']} position={[0.38, 0.115, 0.07]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_65.geometry} material={materials['cover_front.006']} position={[0.384, 0.063, 0.097]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials['cover_back.007']} position={[-0.34, 0.115, -0.02]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials['cover_front.007']} position={[-0.336, 0.063, 0.007]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_85.geometry} material={materials['cover_back.008']} position={[-0.26, 0.115, -0.01]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_87.geometry} material={materials['cover_front.008']} position={[-0.256, 0.063, 0.017]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials['cover_back.009']} position={[-0.18, 0.115, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials['cover_front.009']} position={[-0.176, 0.063, 0.027]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_107.geometry} material={materials['cover_back.010']} position={[-0.1, 0.115, 0.01]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_109.geometry} material={materials['cover_front.010']} position={[-0.096, 0.063, 0.037]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_118.geometry} material={materials['cover_back.011']} position={[-0.02, 0.115, 0.02]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_120.geometry} material={materials['cover_front.011']} position={[-0.016, 0.063, 0.047]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/cdmusic-transformed.glb')
