/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 study.gltf --transform
Author: sedanievansh (https://sketchfab.com/sedanievansh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lofi-hiphop-study-girl-studygirlchallenge-2fcd987b95db4f5fa73b903fe76140a7
Title: Lofi Hiphop Study Girl   #StudyGirlChallenge
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/study-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube005_Material004_0.geometry} material={materials.PaletteMaterial001} position={[448.116, -7.738, 0]} rotation={[-Math.PI / 2, 0, 0.457]} scale={[71.575, 100, 100]} />
    </group>
  )
}

useGLTF.preload('/study-transformed.glb')
